require("nvim-treesitter.install").prefer_git = true

return {
  auto_install = true,
  highlight = {
    enable = true,
    use_languagetree = true,
    additional_vim_regex_highlighting = { "jinja" },
  },
  indent = { enable = true },
  ensure_installed = {
    "lua",
    "luadoc",
    "vim",
    "vimdoc",
    "printf",
    "html",
    "css",
    "diff",
    "json",
    "javascript",
    "jinja",
    "typescript",
    "graphql",
    "prisma",
    "make",
    "c",
    "sql",
    "cpp",
    "rust",
    "go",
    "python",
    "toml",
    "yaml",
    "bash",
    "zig",
  },
}
